# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Yakziry Carbajal
tagline:          'IT Customer Support'
description:      'Tech-savvy problem solver dedicated to enhancing user experiences and operational efficiency'
#url:              https://github.yakziry.com
url:             https://yakziry.com
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Yakziry Carbajal'
  url:            https://yakziry.com


#paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

# Sidebar link settings
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

google_analytics: G-6J81WFKR8C